title: SuperThisMe
description: portfoio for development product by SuperThisMe

url: https://superthisme.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Project
    url: /project
  - title: Contact
    url: /contact

social:
  github: SuperThisMe
  twitter: SuperThisMe
  facebook: SuperThisMe
  email: SuperThisMe

google_analytics: "UA-58263416-111"
